/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_generalplus_ffmpegLib_ffmpegWrapper */

#ifndef _Included_com_generalplus_ffmpegLib_ffmpegWrapper
#define _Included_com_generalplus_ffmpegLib_ffmpegWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef com_generalplus_ffmpegLib_ffmpegWrapper_FFMPEG_STATUS_PLAYING
#define com_generalplus_ffmpegLib_ffmpegWrapper_FFMPEG_STATUS_PLAYING 0L
#undef com_generalplus_ffmpegLib_ffmpegWrapper_FFMPEG_STATUS_STOPPED
#define com_generalplus_ffmpegLib_ffmpegWrapper_FFMPEG_STATUS_STOPPED 1L
#undef com_generalplus_ffmpegLib_ffmpegWrapper_FFMPEG_STATUS_SAVESNAPSHOTCOMPLETE
#define com_generalplus_ffmpegLib_ffmpegWrapper_FFMPEG_STATUS_SAVESNAPSHOTCOMPLETE 2L
#undef com_generalplus_ffmpegLib_ffmpegWrapper_FFMPEG_STATUS_SAVEVIDEOCOMPLETE
#define com_generalplus_ffmpegLib_ffmpegWrapper_FFMPEG_STATUS_SAVEVIDEOCOMPLETE 3L
/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naInitAndPlay
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naInitAndPlay
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naGetVideoInfo
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naGetVideoInfo
  (JNIEnv *, jclass, jstring);


/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naGetVideoRes
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naGetVideoRes
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetup
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetup
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naPlay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naPlay
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naStop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naStop
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naPause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naPause
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naResume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naResume
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSeek
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSeek
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetStreaming
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetStreaming
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetEncodeByLocalTime
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetEncodeByLocalTime
        (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetDebugMessage
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetDebugMessage
        (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetRepeat
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetRepeat
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naGetDuration
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naGetDuration
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naGetPosition
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naGetPosition
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naInitDrawFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naInitDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naDrawFrame
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naDrawFrame
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naStatus
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naGetRevSizeCnt
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naGetRevSizeCnt
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naGetFrameCnt
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naGetFrameCnt
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naGetStreamCodecID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naGetStreamCodecID
        (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSaveSnapshot
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSaveSnapshot
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetForceToTranscode
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetForceToTranscode
        (JNIEnv *, jclass, jboolean);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSaveVideo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSaveVideo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naStopSaveVideo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naStopSaveVideo
  (JNIEnv *, jclass);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naExtractFrame
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naExtractFrame
        (JNIEnv *, jclass, jstring,jstring,jlong);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetTransCodeOptions
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetTransCodeOptions
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetDecodeOptions
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetDecodeOptions
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetScaleMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetScaleMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetCovertDecodeFrameFormat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetCovertDecodeFrameFormat
        (JNIEnv *, jclass, jint);

/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naGetDecodeFrame
 * Signature: ()Lcom/generalplus/ffmpegLib/ffDecodeFrame;
 */
JNIEXPORT jobject JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naGetDecodeFrame
  (JNIEnv *, jclass);


/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetBufferingTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetBufferingTime
        (JNIEnv *, jclass, jlong);


/*
 * Class:     com_generalplus_ffmpegLib_ffmpegWrapper
 * Method:    naSetZoomInRatio
 * Signature: ()Lcom/generalplus/ffmpegLib/ffDecodeFrame;
 */
JNIEXPORT jint JNICALL Java_com_generalplus_ffmpegLib_ffmpegWrapper_naSetZoomInRatio
        (JNIEnv *pEnv, jclass pObj,  jfloat fRatio);

#ifdef __cplusplus
}
#endif
#endif
